version: "3.9" 

services:
  web:
    build:
      context: .
      target: builder
    ports:
      - "8080:80"
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example